# Generated by Django 4.0.2 on 2022-03-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
