# Generated by Django 4.0.2 on 2022-03-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('calc', '0005_remove_calculation_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='calc',
            options={'verbose_name': 'Расчёт', 'verbose_name_plural': 'Расчёты'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.RenameField(
            model_name='calc',
            old_name='calc_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='price_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='price_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='det_heigth',
            new_name='heigth',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='det_material',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='det_width',
            new_name='width',
        ),
        migrations.RemoveField(
            model_name='calc',
            name='calc_date',
        ),
        migrations.RemoveField(
            model_name='calc',
            name='calc_text',
        ),
        migrations.AddField(
            model_name='calc',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='social_django.usersocialauth'),
        ),
        migrations.AddField(
            model_name='calc',
            name='tags',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calc.calctag'),
        ),
    ]
