# Generated by Django 4.0.2 on 2022-03-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_calc_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='material',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='specdetail',
        ),
        migrations.AddField(
            model_name='detail',
            name='calc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calc.calc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='nmb',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='price_material',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена м2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='heigth',
            field=models.PositiveIntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='width',
            field=models.PositiveIntegerField(verbose_name='Ширина'),
        ),
    ]
