# Generated by Django 4.0.2 on 2022-03-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_detail_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='article',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='furniture',
            name='availability',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='furniture',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
        migrations.AddField(
            model_name='furniture',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.CreateModel(
            name='FurnitureInCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('article', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availability', models.CharField(max_length=20)),
                ('nmb', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('furniture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.furniture')),
            ],
        ),
    ]
