# Generated by Django 4.0.2 on 2022-03-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0020_handle_alter_furniture_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'Категория фурнитуры',
                'verbose_name_plural': 'Категории фурнитуры',
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='caterogy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.categoryfurniture'),
        ),
    ]
