# Generated by Django 4.0.2 on 2022-03-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_remove_calculation_tags_delete_post_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
