# Generated by Django 4.0.2 on 2022-03-05 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_calctag_alter_calc_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 5, 11, 27, 34, 777585, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
