# Generated by Django 4.0.2 on 2022-03-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_furnitureincalc_calc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calc',
            name='user',
        ),
    ]
