# Generated by Django 4.0.2 on 2022-03-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_alter_furniture_options_furniture_price_retail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'verbose_name': 'Фурнитура', 'verbose_name_plural': 'Фурнитуры'},
        ),
    ]
