# Generated by Django 4.0.2 on 2022-03-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0018_alter_furniture_price_retail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='price_retail',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
