# Generated by Django 4.0.2 on 2022-03-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0021_categoryfurniture_furniture_caterogy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='caterogy',
            new_name='category',
        ),
    ]
