# Generated by Django 4.1.2 on 2023-07-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0026_alter_ldstp_options_alter_furniture_availability_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=1000, verbose_name="Текст комментария"),
        ),
    ]
