# Generated by Django 4.1.2 on 2023-07-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0027_alter_comment_options_rename_name_comment_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detail",
            old_name="heigth",
            new_name="height",
        ),
    ]
