# Generated by Django 4.1.2 on 2023-07-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_alter_tag_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["title"],
                "verbose_name": "Тэг к статье",
                "verbose_name_plural": "Тэги к статьям",
            },
        ),
    ]
