# Generated by Django 4.0.2 on 2022-03-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_remove_calc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название расчёта'),
        ),
        migrations.AlterField(
            model_name='furnitureincalc',
            name='furniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calc.furniture'),
        ),
    ]
