# Generated by Django 4.0.2 on 2022-03-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_alter_calc_title_alter_furnitureincalc_furniture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'verbose_name': 'Расчёт', 'verbose_name_plural': 'Расчёты'},
        ),
        migrations.AddField(
            model_name='furniture',
            name='price_retail',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name='furnitureincalc',
            name='price_retail',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='furnitureincalc',
            name='furniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calc.furniture'),
        ),
    ]
