# Generated by Django 4.0.2 on 2022-03-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0023_delete_handle_alter_calctag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ldstp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availability', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name='furnitureincalc',
            options={'verbose_name': 'Фурнитура в расчёте', 'verbose_name_plural': 'Фурнитура в расчёте'},
        ),
    ]
