# Generated by Django 4.0.2 on 2022-03-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0024_ldstp_alter_furnitureincalc_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationdetail',
            name='calculation',
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Текст коментария'),
        ),
        migrations.DeleteModel(
            name='Calculation',
        ),
        migrations.DeleteModel(
            name='SpecificationDetail',
        ),
    ]
