# Generated by Django 4.1.2 on 2022-10-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0025_remove_specificationdetail_calculation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ldstp",
            options={"verbose_name": "ЛДСП", "verbose_name_plural": "ЛДСП"},
        ),
        migrations.AlterField(
            model_name="furniture",
            name="availability",
            field=models.CharField(default=None, max_length=20, verbose_name="Наличие"),
        ),
        migrations.AlterField(
            model_name="furnitureincalc",
            name="article",
            field=models.CharField(max_length=50, verbose_name="Артикул"),
        ),
        migrations.AlterField(
            model_name="furnitureincalc",
            name="availability",
            field=models.CharField(max_length=20, verbose_name="Наличие"),
        ),
        migrations.AlterField(
            model_name="furnitureincalc",
            name="nmb",
            field=models.PositiveIntegerField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="furnitureincalc",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Оптовая цена"
            ),
        ),
        migrations.AlterField(
            model_name="furnitureincalc",
            name="price_retail",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=8, verbose_name="Розничная цена"
            ),
        ),
        migrations.AlterField(
            model_name="furnitureincalc",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="furnitureincalc",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Итого"
            ),
        ),
    ]
